### ISSUE TITLE
alsa/asoundlib.h

### ISSUE THREAD

**Issue by Morvell** [supergilbert/midilooper#1]
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Imidiseq/ -I/usr/include/python3.5m -c midiseq/asound/aseq.c -o build/temp.linux-x86_64-3.5/midiseq/asound/aseq.o -Wall -Werror
In file included from midiseq/asound/aseq.c:19:0:
midiseq/asound/aseq.h:22:28: fatal error: alsa/asoundlib.h: Нет такого файла или каталога
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by supergilbert** [comment]
I think this error is because dependencies is missing you should install
libasound and check the README for dependencies.

(I am not russian but google trad say "Нет такого файла или каталога" means
"No such file or directory")
