### ISSUE TITLE
Midi Channel UI displays wrong ch number

### ISSUE THREAD

**Issue by CarloCattano** [supergilbert/midilooper#3]
https://github.com/supergilbert/midilooper/blob/c2c080f4fc3bf6da3d80ad62588e3b84a0ccc537/src/midilooper/msq_track_editor.c#L197

Midi Ch1 = 0

Selecting midi Ch 6 on midilooper will effectively send on midi Ch 7 to the midi device. To avoid confusion would be better to make it match .
 Not sure if its enough renaming since maybe other parts of the code will break . 

[reference:](https://www.cs.cmu.edu/~music/cmsip/readings/MIDI%20tutorial%20for%20programmers.html)
 
>  There are 16 possible MIDI channels, numbered from 0 to 15 in hexadecimal. In practice, musicians and software refer to the MIDI channels by counting them from 1 to 16, so that there is a difference of 1 when you program them in hexadecimal (channel "1" is coded "0", channel "10" is coded "9" and channel 16 is coded "F").

**Comment by CarloCattano** [comment]
https://github.com/supergilbert/midilooper/pull/4
My first PR ever !  
:-)

**Comment by supergilbert** [comment]
Well done.
It is merged

**Comment by supergilbert** [comment]
(I know that channel label does not really follow midi spec but for now, I make all indexes start at 0. I will check good labels later)
